config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :employees
  resources :teams
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :team, optional: true

  validates :name, presence: true
  validates :mobile, presence: true, length: { is: 10 }, format: { with: /\A[1-9]\d*\z/ } , uniqueness: true
  validates :address, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP } , uniqueness: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :manager, class_name: 'Employee', foreign_key: 'manager_id', optional: true
  has_many :employees, foreign_key: 'team_id', dependent: :nullify

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def new
        @employee = Employee.new
    end

    def edit
        @employee = Employee.find(params[:id])
    end

    def create 
        @employee = Employee.new(employee_params)
       
        
        if @employee.save
            if(@employee.is_manager)
                if(@employee.team.manager)
                    @employee.team.manager.is_manager = false
                    @employee.team.manager.save
                end
                @employee.team.manager_id = @employee.id
                @employee.team.save
            end
            redirect_to @employee
        else
            render 'new'
        end
    end

    def update
        @employee = Employee.find(params[:id])
        employee1 = Employee.find(params[:id])
        employee2 = employee1.team ? employee1.team.manager : nil

        if(@employee.team)
            @employee.team.manager_id = nil
            @employee.team.save
        end
       
        if @employee.update(employee_params)
            if(@employee.is_manager == true)
                if(employee2 && employee2.team_id == @employee.team_id)
                    employee2.is_manager = 0
                    employee2.save
                elsif(@employee.team.manager)
                    @employee.team.manager.is_manager = false
                    @employee.team.manager.save
                end
                @employee.team.manager_id = @employee.id
                @employee.team.save
            else
                if(employee2 && @employee.id != employee2.id)
                    employee1.team.manager_id = employee2.id
                    employee1.team.save
                end
            end
            redirect_to @employee
        else
           render 'edit'
        end
    end

    def destroy
        @employee = Employee.find(params[:id])

        if @employee.is_manager?
            @employee.team.manager_id = nil
            @employee.team.save
        end

        @employee.destroy
       
        redirect_to employees_path
    end

    def show
        @employee = Employee.find(params[:id])
    end

    def index
        @employees = Employee.all
    end

    private

    def employee_params
        params.require(:employee).permit(:name,:email,:address,:mobile, :team_id,:is_manager)
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    def new
        @team = Team.new
    end

    def edit
        @team = Team.find(params[:id])
    end

    def create 
        @team = Team.new(team_params)
    

        if @team.save
            if(@team.manager)
                @team.manager.team_id = @team.id
                @team.manager.is_manager = true
                @team.manager.save
            end
            redirect_to @team
        else
            render 'new'
        end
    end

    def update
        @team = Team.find(params[:id])
        puts @team.inspect
        if(@team.manager)
            @team.manager.team_id = nil
            @team.manager.is_manager = false
            @team.manager.save
        end

        if @team.update(team_params)
            if(@team.manager)
                @team.manager.team_id = @team.id
                @team.manager.is_manager = true
                @team.manager.save
            end
            
            redirect_to @team
        else
          render 'edit'
        end
    end

    def show
        @team = Team.find(params[:id])
    end

    def index
        @teams = Team.all
    end

    def destroy
        @team = Team.find(params[:id])
        if(@team.manager)
            @team.manager.is_manager = false
            @team.manager.save
        end

        @team.destroy
        redirect_to teams_path
    end

    

    private

    def team_params
        params.require(:team).permit(:name,:manager_id,employee_ids: [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_form.html.erb
<div class="center-container">
  <%= form_with model: @employee, local: true do |form| %>
    <% if @employee.errors && @employee.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@employee.errors.count, "error") %> prohibited
          this employee from being saved:
        </h2>
        <ul>
          <% @employee.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>

  <p>
    <%= form.label :mobile %><br>
    <%= form.text_field :mobile %>
  </p>

  <p>
    <%= form.label :team_id %><br>
    <%= form.collection_select :team_id, [OpenStruct.new(id: nil, name: "No Team")] + Team.all, :id, :name, prompt: 'Select Team' %>
  </p>

  <p id="is-manager-section" style="display: none;">
    <%= form.label :is_manager %>
    <%= form.check_box :is_manager %>
  </p>

  <p class="submit-button">
    <%= form.submit %>
  </p>
  <% end %>
  </div>

  <script>
      var teamSelect = document.getElementById('employee_team_id');
      var isManagerSection = document.getElementById('is-manager-section');
      var isManagerCheckbox = document.getElementById('employee_is_manager');

      document.querySelectorAll('.add-team').forEach(function(element) {
        element.style.display = 'none';
      });

      teamSelect.addEventListener('change', function () {
        isManagerCheckbox.checked = false;
        isManagerSection.style.display = this.value ? 'block' : 'none';
      });

      isManagerSection.style.display = teamSelect.value ? 'block' : 'none';
  </script>

app/views/employees/_header.html.erb
<style>
  body {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding-top:100px;
    margin: 0;
    font-family: Arial, sans-serif;
    background-color: #121212;
    color: #ffffff;
  }
</style>

<div class="header">
  <%= link_to(controller: 'welcome') do %>
     <i class="bi bi-arrow-left-circle-fill back-button"></i> 
  <% end %>
  <h1>Employee Details</h1>
  <%= link_to(new_employee_path) do %>
     <i class="bi bi-plus-circle add-team"></i> 
  <% end %>
</div>

app/views/employees/_header1.html.erb
<style>
  body {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding-top:100px;
    margin: 0;
    font-family: Arial, sans-serif;
    background-color: #121212;
    color: #ffffff;
  }
</style>

<div class="header">
  <%= link_to(employees_path) do %>
     <i class="bi bi-arrow-left-circle-fill back-button"></i> 
  <% end %>
  <h1>Employee Detail</h1>
  <%= link_to(new_employee_path) do %>
     <i class="bi bi-plus-circle add-team"></i> 
  <% end %>
</div>

app/views/employees/_header2.html.erb
<style>
  body {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding-top:100px;
    margin: 0;
    font-family: Arial, sans-serif;
    background-color: #121212;
    color: #ffffff;
  }
</style>

<div class="header">
  <%= link_to(employees_path) do %>
     <i class="bi bi-arrow-left-circle-fill back-button"></i> 
  <% end %>
  <h1>Teams - <%=@employee.name%></h1>
  <%= link_to edit_employee_path(@employee), class: "bi bi-pencil-square edit-team" do %>
  <% end %>
</div>

app/views/employees/edit.html.erb
<%= render 'header1'%>
<%= render 'form' %>

app/views/employees/index.html.erb
<style>
  body {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding-top:100px;
    margin: 0;
    font-family: Arial, sans-serif;
    background-color: #121212;
    color: #ffffff;
  }
</style>

<%= render 'header'%>
<div class="main-container">
  <% @employees.each do |employee| %>
    <a href="<%= employee_path(employee) %>" class="team-link">
    <div class="team-container">
      <div class="team-details">
        <div class="detail">
          <strong>Name:</strong> <%= employee.name %>
        </div>
        <div class="detail">
          <strong>Email:</strong> <%= employee.email %>
        </div>
        <div class="detail">
          <strong>Team:</strong> <%= employee.team ? employee.team.name : 'Not Assigned' %>
        </div>
      </div>
      <div class="actions">
        <%= link_to edit_employee_path(employee),
            class: "bi bi-pencil-square" do %>
        <% end %>
        <%= link_to employee_path(employee),
            method: :delete,
            data: { confirm: 'Are you sure?' },
            class: "bi bi-trash3-fill" do %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/employees/new.html.erb
<%= render 'header1'%>
<%= render 'form' %>

app/views/employees/show.html.erb
<%= render 'header2'%>
<div class="center-container1">
  <div class="data-container">
  <p>
    <strong>Name:</strong>
    <%= @employee.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @employee.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @employee.address %>
  </p>

  <p>
    <strong>Mobile:</strong>
    <%= @employee.mobile %>
  </p>

  <% if @employee.team.present? %>
    <p>
      <strong>Team:</strong>
      <%= @employee.team.name %>
    </p>

    <% if @employee.is_manager? %>
      <p>
        <strong>Role:</strong> He/She is the manager of this team 
      </p>
    <% else %>
      <p>
        <strong>Manager:</strong> 
        <% if @employee.team.manager %>
          <%= @employee.team.manager.name %>
        <% else %>
          Not assigned
        <% end %>
      </p>
    <% end %>
  <% else %>
    <p>
      <strong>Team:</strong> haven't been assigned to a team yet.
    </p>
  <% end %>
 </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
  <style>
    body {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      margin: 0;
      font-family: Arial, sans-serif;
      background-color: #121212;
      color: #ffffff;
    }
  </style>
  <div class="content-container">
    <h1>Welcome to Employee Management System</h1>
    <div class="link-box">
      <a href="<%= teams_path %>">Go to Team Details</a>
    </div>
    <div class="link-box">
      <a href="<%= employees_path %>">Go to Employee Details</a>
    </div>
  </div>